version: "3"

# volumes:
#     telegram-bot-api-data:
#     static-data:

services:
  # bot-api:
  #   platform: linux/x86_64
  #   image: aiogram/telegram-bot-api:6.7.1
  #   restart: always
  #   expose:
  #     - "8081"
  #   environment:
  #     - TELEGRAM_API_ID=${TELEGRAM_API_ID}
  #     - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
  #     - TELEGRAM_VERBOSITY=3
  #     - TELEGRAM_LOCAL=1
  #   volumes:
  #     - telegram-bot-api-data:/var/lib/telegram-bot-api
  #     - static-data:/code/bot/static

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - ${MONGODB_PATH}:/data/db

  bot:
    command: python3 run.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
      # - bot-api
    # volumes:
    #   - telegram-bot-api-data:/var/lib/telegram-bot-api
    #   - static-data:/code/bot/static

  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo

  # jupyter:
  #   command: jupyter notebook --ip=0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='${JUPYTER_TOKEN}'
  #   restart: always
  #   build:
  #     context: "."
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${JUPYTER_PORT}:8888
  #   volumes:
  #     - ./:/code
  #   depends_on:
  #     - mongo

